#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 28 23:57:17 2019

@author: asahay
"""

print("Hello World")
print("Still no progress with OpenCV")
print("Will do open CV parallely with work")